import { useEffect, useMemo, useState } from "react";
import {
  getAdminNotifications,
  getNotificationSummary,
  markNotificationAsRead,
  type AdminNotification,
  type NotificationSummary,
} from "../api/notifications";

type ReadFilter = "" | "unread" | "read";

function recipientName(notification: AdminNotification) {
  const name = [
    notification.recipient?.firstName,
    notification.recipient?.lastName,
  ]
    .filter(Boolean)
    .join(" ");

  return name || notification.recipient?.email || "Unknown recipient";
}

function formatDate(value: string) {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toLocaleString();
}

function NotificationCenter() {
  const [summary, setSummary] = useState<NotificationSummary | null>(null);
  const [notifications, setNotifications] = useState<AdminNotification[]>([]);
  const [readFilter, setReadFilter] = useState<ReadFilter>("");
  const [typeFilter, setTypeFilter] = useState("");
  const [loading, setLoading] = useState(true);
  const [actionId, setActionId] = useState("");
  const [error, setError] = useState("");

  const notificationTypes = useMemo(() => {
    return Array.from(
      new Set(notifications.map((notification) => notification.type)),
    ).sort();
  }, [notifications]);

  async function loadNotifications() {
    try {
      setLoading(true);
      setError("");

      const read =
        readFilter === "unread"
          ? false
          : readFilter === "read"
            ? true
            : undefined;

      const [summaryData, notificationData] = await Promise.all([
        getNotificationSummary(),
        getAdminNotifications({
          read,
          type: typeFilter || undefined,
        }),
      ]);

      setSummary(summaryData);
      setNotifications(notificationData);
    } catch {
      setError("Unable to load Notification Center.");
    } finally {
      setLoading(false);
    }
  }

  async function handleMarkAsRead(id: string) {
    try {
      setActionId(id);
      setError("");

      const updated = await markNotificationAsRead(id);

      setNotifications((current) =>
        current.map((notification) =>
          notification.id === id ? updated : notification,
        ),
      );

      setSummary((current) =>
        current
          ? {
              ...current,
              unread: Math.max(0, current.unread - 1),
              read: current.read + 1,
            }
          : current,
      );
    } catch {
      setError("Unable to mark the notification as read.");
    } finally {
      setActionId("");
    }
  }

  useEffect(() => {
    void loadNotifications();
  }, [readFilter, typeFilter]);

  return (
    <section className="module-workspace notification-center-workspace">
      <div className="module-header">
        <span className="module-kicker">
          TRANSCONET-APEX1 GOVERNANCE
        </span>

        <h2>Notification Center</h2>

        <p>
          Monitor platform notifications and acknowledge operational
          events generated across the TransConet-Apex1 ecosystem.
        </p>
      </div>

      {error && (
        <div className="module-card module-error">
          <strong>Notification Center unavailable</strong>
          <p>{error}</p>
        </div>
      )}

      <div className="stats-grid">
        <div className="stat-card">
          <span>Total Notifications</span>
          <strong>{loading ? "…" : summary?.total ?? 0}</strong>
          <small>All platform notifications</small>
        </div>

        <div className="stat-card">
          <span>Unread</span>
          <strong>{loading ? "…" : summary?.unread ?? 0}</strong>
          <small>Awaiting acknowledgement</small>
        </div>

        <div className="stat-card">
          <span>Read</span>
          <strong>{loading ? "…" : summary?.read ?? 0}</strong>
          <small>Previously acknowledged</small>
        </div>

        <div className="stat-card">
          <span>Visible Events</span>
          <strong>{loading ? "…" : notifications.length}</strong>
          <small>Matching current filters</small>
        </div>
      </div>

      <div className="module-card">
        <div className="module-toolbar">
          <div>
            <strong>Platform notification stream</strong>
            <span>
              Operational notifications generated by authorized platform
              services.
            </span>
          </div>

          <div className="module-controls">
            <label>
              <span>Read status</span>
              <select
                value={readFilter}
                onChange={(event) =>
                  setReadFilter(event.target.value as ReadFilter)
                }
              >
                <option value="">All</option>
                <option value="unread">Unread</option>
                <option value="read">Read</option>
              </select>
            </label>

            <label>
              <span>Type</span>
              <select
                value={typeFilter}
                onChange={(event) => setTypeFilter(event.target.value)}
              >
                <option value="">All types</option>
                {notificationTypes.map((type) => (
                  <option key={type} value={type}>
                    {type}
                  </option>
                ))}
              </select>
            </label>

            <button
              type="button"
              className="refresh-button"
              onClick={() => void loadNotifications()}
              disabled={loading}
            >
              {loading ? "Refreshing…" : "Refresh"}
            </button>
          </div>
        </div>
      </div>

      <div className="module-card">
        <div className="panel-header">
          <div>
            <h2>Notifications</h2>
            <p>
              {notifications.length} notification
              {notifications.length === 1 ? "" : "s"} returned
            </p>
          </div>

          <span className="live-badge">
            <span className="status-dot" />
            PLATFORM
          </span>
        </div>

        {loading ? (
          <div className="module-empty">
            <strong>Loading notifications…</strong>
          </div>
        ) : notifications.length === 0 ? (
          <div className="module-empty">
            <strong>No notifications found</strong>
            <span>
              There are no notifications matching the current filters.
            </span>
          </div>
        ) : (
          <div className="notification-list">
            {notifications.map((notification) => (
              <article
                key={notification.id}
                className={`notification-item ${
                  notification.read ? "notification-read" : "notification-unread"
                }`}
              >
                <div className="notification-indicator">
                  {notification.read ? "✓" : "!"}
                </div>

                <div className="notification-content">
                  <div className="notification-heading">
                    <div>
                      <strong>{notification.title}</strong>
                      <span className="notification-type">
                        {notification.type}
                      </span>
                    </div>

                    <time>{formatDate(notification.createdAt)}</time>
                  </div>

                  <p>{notification.message}</p>

                  <div className="notification-meta">
                    <span>
                      Recipient: <strong>{recipientName(notification)}</strong>
                    </span>

                    {notification.relatedType && (
                      <span>
                        Related:{" "}
                        <strong>{notification.relatedType}</strong>
                        {notification.relatedId
                          ? ` / ${notification.relatedId}`
                          : ""}
                      </span>
                    )}

                    {!notification.read && (
                      <button
                        type="button"
                        className="text-button"
                        disabled={actionId === notification.id}
                        onClick={() =>
                          void handleMarkAsRead(notification.id)
                        }
                      >
                        {actionId === notification.id
                          ? "Updating…"
                          : "Mark as read"}
                      </button>
                    )}
                  </div>
                </div>
              </article>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}

export default NotificationCenter;
